from Raiden import (DEV_USERS, WHITELIST_USERS, SUPPORT_USERS, DEMONS, telethn)

IMMUNE_USERS = WHITELIST_USERS + SUPPORT_USERS + DEMONS + DEV_USERS

IMMUNE_USERS = list(WHITELIST_USERS) + list(SUPPORT_USERS) + list(DEMONS) + list(DEV_USERS)
